services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Kematjaya\HiddenTypeBundle\Type\HiddenEntityType: ~
    Kematjaya\HiddenTypeBundle\Type\HiddenDateTimeType: ~
